title: Suspicious Blog
author: Suspicious Magazine
email: support@suspcs.xyz
url: https://suspcs.xyz
description: A very suspiocious blog.
permalink: /blog/:slug

favicon: "./img/logo.png"

theme_config:
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

plugins:
  - jekyll-feed
  - jekyll-seo-tag
